theme: jekyll-theme-cayman
description: Development of an Accessible Camera-based System for Measuring Hand Joint Range of Motion

remote_theme: tuur29/pages-themes-cayman
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
google_analytics_anonymize: false
darkmode: false
hide_first_title: false # Useful if README.md is used on both github and pages
syntax_theme: # Leave empty for default, otherwise link to a pygments stylesheet
colors:
    gradient_left: "#D71440"
    gradient_right: "#181C62"
    header: "#fff"
