title: Development of an Accessible Camera-based System for Measuring Hand Joint Range of Motion
remote_theme: tuur29/pages-themes-cayman
color:
    gradient_left: "#D71440"
    gradient_right: "#181C62"
    header: "#fff"
buttons:
  zip_hide: true
  tar_hide: true
  github_hide: true
